apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sensor-simulator.fullname" . }}
  labels:
    {{- include "sensor-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sensor-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sensor-simulator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: {{ include "goal-event-service.fullname" . }}
          env:
            - name: GOAL_DEVICE_SERVICE
              value: {{ .Values.goalDeviceService.host }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 0
            periodSeconds: 1
      restartPolicy: Always
