apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: rgb-goal-data-service
spec:
  prefix: /rgb/api/goal/
  service: rgb-goal-data-service
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: rgb-goal-event-service
spec:
  prefix: /rgb/api/goal/events/
  service: rgb-goal-event-service
  allow_upgrade:
    - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: rgb-goal-device-service
spec:
  prefix: /rgb/api/device/
  service: rgb-goal-device-service
  allow_upgrade:
    - websocket
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: rgb-frontend-web
spec:
  prefix: /rgb/
  service: rgb-frontend-web
