apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goal-device-service.fullname" . }}
  labels:
    {{- include "goal-device-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goal-device-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goal-device-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: {{ include "goal-device-service.fullname" . }}
      restartPolicy: Always
