apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goal-data-service.fullname" . }}
  labels:
    {{- include "goal-data-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goal-data-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goal-data-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: {{ include "goal-event-service.fullname" . }}
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rgb-secrets
                  key: mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rgb-secrets
                  key: mongodb-password
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.database }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 0
            periodSeconds: 1
      restartPolicy: Always
