apiVersion: v1
kind: Service
metadata:
  name: {{ include "goal-data-service.fullname" . }}
  labels:
    {{- include "goal-data-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "goal-data-service.selectorLabels" . | nindent 4 }}
