apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goal-event-processor.fullname" . }}
  labels:
    {{- include "goal-event-processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "goal-event-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "goal-event-processor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: {{ include "goal-event-processor.fullname" . }}
          env:
            - name: KAFKA_HOST
              value: {{ .Values.kafka.host }}
            - name: GOAL_DATA_SERVICE_HOST
              value: {{ .Values.goalDataService.host }}
      restartPolicy: Always
